SetAPSServo(13,0,600)
SetAPSServo(14,0,600)
SetAPSServo(15,0,600)
SetAPSServo(16,0,600)

status =  GetAPSRTStatus()
print("Pitch  :".. status.Real_Pitch)
print("Roll   :".. status.Real__Roll)
print("Speed_X:".. status.Speed_X)
print("Speed_Y:".. status.Speed_Y)
print("Speed_Z:".. status.Speed_Z)
print("Move_X :".. status.Move_X)
print("Move_Y :".. status.Move_Y)
print("Move_Z :".. status.Move_Z)

